# PyTorch Fundamentals


In [ ]:
# Install pytorch
!pip install torch torchvision torchaudio

In [2]:
# Check for Cuda based CPU
!nvidia-smi

zsh:1: command not found: nvidia-smi


In [ ]:
import torch
import numpy as np
import pandas as pd

# import matplotlib.pyplot as plt

print(torch.__version__)

2.5.1


## Creating Tensors


In [9]:
# Scalar - Scalar has no dimensions
scalar = torch.tensor(7)
scalar, scalar.ndim, scalar.shape

(tensor(7), 0, torch.Size([]))

In [31]:
# Genting tensor back as python int
scalar.item(), type(scalar.item()), scalar.numpy()

(7, int, array(7))

In [21]:
# Vector - Vectors has single dimension
vector = torch.tensor([2, 2])
vector, vector.ndim, vector.shape

(tensor([2, 2]), 1, torch.Size([2]))

In [22]:
# Vectore or any high dimensinal representation can't be converted into basic python datatypes
vector.item()

RuntimeError: a Tensor with 2 elements cannot be converted to Scalar

In [23]:
# Higher dimension tensors can be converted into numpy arrays
vector.numpy(), type(vector.numpy())

(array([2, 2]), numpy.ndarray)

In [24]:
# Matrix - matrix has 3 dimensions

MATRIX = torch.tensor([[1, 2], [4, 5]])

MATRIX, MATRIX.ndim, MATRIX.shape

(tensor([[1, 2],
         [4, 5]]),
 2,
 torch.Size([2, 2]))

In [25]:
# Converting the matrix into numpy array
MATRIX.numpy()

array([[1, 2],
       [4, 5]])

In [ ]:
# Tensor - Any representation which is higher than 2 dimensions are called tensor
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [6,7,8]]])

TENSOR, TENSOR.ndim, TENSOR.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [6, 7, 8]]]),
 3,
 torch.Size([1, 3, 3]))

In [29]:
# Let's create a high dimensional tensor
TENSOR1 = torch.tensor([
    [
        [1,2,3],
        [2,3,4],
        [4,5,6]
    ],
    [
        [2,3,4],
        [3,4,5],
        [4,5,6]
    ],
    [
        [5,6,7],
        [6,7,8],
        [7,8,9]
    ]
])

TENSOR1, TENSOR1.ndim, TENSOR1.shape

(tensor([[[1, 2, 3],
          [2, 3, 4],
          [4, 5, 6]],
 
         [[2, 3, 4],
          [3, 4, 5],
          [4, 5, 6]],
 
         [[5, 6, 7],
          [6, 7, 8],
          [7, 8, 9]]]),
 3,
 torch.Size([3, 3, 3]))

In [30]:
TENSOR1.numpy()

array([[[1, 2, 3],
        [2, 3, 4],
        [4, 5, 6]],

       [[2, 3, 4],
        [3, 4, 5],
        [4, 5, 6]],

       [[5, 6, 7],
        [6, 7, 8],
        [7, 8, 9]]])

In [32]:
# Creating random tensors

RANDOM_TENSOR = torch.rand(3,3)
RANDOM_TENSOR, RANDOM_TENSOR.ndim, RANDOM_TENSOR.shape

(tensor([[0.0823, 0.9386, 0.2882],
         [0.5603, 0.2029, 0.8637],
         [0.8846, 0.4053, 0.4222]]),
 2,
 torch.Size([3, 3]))

In [33]:
RANDOM_TENSOR1 = torch.rand(3,2,3)
RANDOM_TENSOR1, RANDOM_TENSOR1.ndim, RANDOM_TENSOR1.shape

(tensor([[[9.8578e-01, 8.1515e-04, 2.3163e-01],
          [5.7306e-01, 5.3345e-02, 5.6700e-01]],
 
         [[1.1941e-01, 3.8047e-02, 5.2982e-01],
          [5.4047e-01, 6.2658e-03, 1.7898e-01]],
 
         [[3.0821e-01, 9.8298e-01, 2.5448e-01],
          [7.1243e-01, 8.6101e-01, 2.3488e-01]]]),
 3,
 torch.Size([3, 2, 3]))

In [36]:
RANDOM_TENSOR2 = torch.rand(3,4,1)
RANDOM_TENSOR2, RANDOM_TENSOR2.ndim, RANDOM_TENSOR2.shape

(tensor([[[0.1646],
          [0.6202],
          [0.5110],
          [0.7288]],
 
         [[0.1149],
          [0.5530],
          [0.6424],
          [0.5867]],
 
         [[0.9275],
          [0.8683],
          [0.4266],
          [0.0999]]]),
 3,
 torch.Size([3, 4, 1]))

In [38]:
# Usually 3 dimensional are used to represent the image - height, width, colour channels
IMAGE_TENSOR = torch.rand(128,128,3) # There are 3 colour channels RGB
IMAGE_TENSOR, IMAGE_TENSOR.ndim, IMAGE_TENSOR.shape

(tensor([[[0.4908, 0.1631, 0.6877],
          [0.1832, 0.2233, 0.3894],
          [0.0593, 0.2149, 0.5402],
          ...,
          [0.2437, 0.1051, 0.8612],
          [0.3675, 0.9235, 0.3517],
          [0.4929, 0.3742, 0.4066]],
 
         [[0.5611, 0.1014, 0.7051],
          [0.2625, 0.8378, 0.6856],
          [0.6474, 0.5882, 0.3454],
          ...,
          [0.0592, 0.6731, 0.5259],
          [0.2657, 0.7419, 0.8685],
          [0.0282, 0.8033, 0.6557]],
 
         [[0.5855, 0.8774, 0.1039],
          [0.8938, 0.4146, 0.3714],
          [0.2301, 0.1166, 0.9523],
          ...,
          [0.8816, 0.0409, 0.3102],
          [0.7642, 0.1526, 0.8095],
          [0.4319, 0.9481, 0.8615]],
 
         ...,
 
         [[0.0800, 0.9441, 0.1036],
          [0.7439, 0.1061, 0.4440],
          [0.5982, 0.2064, 0.9190],
          ...,
          [0.9902, 0.7669, 0.2473],
          [0.9070, 0.4428, 0.5059],
          [0.8208, 0.6711, 0.5792]],
 
         [[0.9453, 0.5077, 0.9160],
          [0

In [39]:
# Sometimes the colour channels are represented in first dimension - colour channels, height, width
IMAGE_TENSOR1 = torch.rand(3, 128, 128)
IMAGE_TENSOR1, IMAGE_TENSOR1.ndim, IMAGE_TENSOR1.shape

(tensor([[[0.0971, 0.1804, 0.9167,  ..., 0.7599, 0.6302, 0.4564],
          [0.1572, 0.8615, 0.9748,  ..., 0.9499, 0.0570, 0.1486],
          [0.4153, 0.6198, 0.9386,  ..., 0.6616, 0.2318, 0.7932],
          ...,
          [0.6448, 0.9474, 0.5037,  ..., 0.5918, 0.4951, 0.2397],
          [0.8033, 0.5629, 0.0896,  ..., 0.5762, 0.0442, 0.6353],
          [0.4749, 0.9245, 0.8320,  ..., 0.3005, 0.5808, 0.4453]],
 
         [[0.5025, 0.0504, 0.6066,  ..., 0.7590, 0.9262, 0.8576],
          [0.6012, 0.0135, 0.5251,  ..., 0.9850, 0.1128, 0.9943],
          [0.1797, 0.6717, 0.4255,  ..., 0.2188, 0.6588, 0.4844],
          ...,
          [0.2162, 0.1267, 0.0266,  ..., 0.5170, 0.6924, 0.2608],
          [0.1824, 0.5920, 0.0161,  ..., 0.0020, 0.4412, 0.9079],
          [0.4803, 0.4572, 0.6586,  ..., 0.7952, 0.6895, 0.5079]],
 
         [[0.8091, 0.2805, 0.2604,  ..., 0.7331, 0.6482, 0.0912],
          [0.5453, 0.8000, 0.1026,  ..., 0.3908, 0.8612, 0.2298],
          [0.4946, 0.8606, 0.2847,  ...,

In [40]:
# Creating tensors for zeros and ones
# This shall be used to create mask
ZERO_TENSOR = torch.zeros(3,3)
ZERO_TENSOR, ZERO_TENSOR.ndim, ZERO_TENSOR.shape

(tensor([[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]),
 2,
 torch.Size([3, 3]))

In [41]:
ONE_TENSOR = torch.ones(3,3)
ONE_TENSOR, ONE_TENSOR.ndim, ONE_TENSOR.shape

(tensor([[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]),
 2,
 torch.Size([3, 3]))

In [43]:
# By default the tensors are created as float32
ONE_TENSOR.dtype

torch.float32

In [44]:
# We could create tensors with different datatypes
RANDOM_TENSOR3 = torch.rand(3,3, dtype=torch.float16)
RANDOM_TENSOR3, RANDOM_TENSOR3.dtype

(tensor([[0.8140, 0.9263, 0.3369],
         [0.7725, 0.4858, 0.7134],
         [0.9590, 0.5430, 0.0967]], dtype=torch.float16),
 torch.float16)

In [65]:
# Creating rand tensors with type bfloat16 - binary float 16
# This is a newer datatype which shall use 16 bits for each element in the tensor but supports higher precision due to it's bits distribution
RANDOM_TENSOR4 = torch.rand(2,2, dtype=torch.bfloat16)
RANDOM_TENSOR4, RANDOM_TENSOR4.dtype

(tensor([[0.1680, 0.3086],
         [0.5273, 0.7539]], dtype=torch.bfloat16),
 torch.bfloat16)

In [49]:
# Creating a range of tensors
RANGE_TENSOR = torch.arange(0,9)
RANGE_TENSOR, RANGE_TENSOR.ndim, RANGE_TENSOR.shape

(tensor([0, 1, 2, 3, 4, 5, 6, 7, 8]), 1, torch.Size([9]))

In [50]:
# Creating a range of tensor with steps
RANGE_TENSOR1 = torch.arange(start=1, end=1000, step=100)
RANGE_TENSOR1, RANGE_TENSOR1.dtype

(tensor([  1, 101, 201, 301, 401, 501, 601, 701, 801, 901]), torch.int64)

In [51]:
# Creating tensors like - creating tensors like different tensors
LIKE_TENSOR = torch.ones_like(RANGE_TENSOR1)
LIKE_TENSOR, LIKE_TENSOR.dtype, LIKE_TENSOR.ndim, LIKE_TENSOR.shape

(tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1]), torch.int64, 1, torch.Size([10]))

In [60]:
# Similarly we could create like tensors of zeros 
LIKE_TENSOR1 = torch.zeros_like(RANGE_TENSOR1)
LIKE_TENSOR1, LIKE_TENSOR1.dtype, LIKE_TENSOR1.shape

(tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), torch.int64, torch.Size([10]))

In [61]:
# Important args while creating tensors
# dtype - defines the datatype of the tensor
# device - defines the device the tensor need to be created - could be cuda if cuda based GPU is available
# requires_grad - this will define that the gradiants need to be calculated during the processing - this will be helpful in training stage
RANDOM_TENSOR5 = torch.rand(3,3, dtype=torch.bfloat16, device='cpu', requires_grad=False)
RANDOM_TENSOR5, RANDOM_TENSOR5.dtype, RANDOM_TENSOR5.device

(tensor([[0.8984, 0.2852, 0.5391],
         [0.9883, 0.2891, 0.7422],
         [0.8750, 0.0977, 0.4570]], dtype=torch.bfloat16),
 torch.bfloat16,
 device(type='cpu'))

In [64]:
RANDOM_TENSOR6 = torch.rand(2,2, dtype=torch.bfloat16, device=None, requires_grad=False)
RANDOM_TENSOR6, RANDOM_TENSOR6.dtype, RANDOM_TENSOR6.device

(tensor([[0.9922, 0.6406],
         [0.3555, 0.5781]], dtype=torch.bfloat16),
 torch.bfloat16,
 device(type='cpu'))